### ISSUE TITLE
Named revision won't deploy

### ISSUE THREAD

**Issue by averikitsch** [google-github-actions/deploy-cloudrun#12]
### TL;DR
Naming a revision using YAML metadata, will not deploy with correct revision name.

**Expected behavior**
Deployed with revision name (either replace or update).

**Observed behavior**
Deployed to a generated revision name with error `Revision 'NAME' does not exist or is deleted`.

### Reproduction

**Action YAML**

```yaml
 - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@main
      with:
        metadata: service.yaml
```

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: NAME
  annotations:
        run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      name: NAME-002
    spec:
      containers:
      - image: gcr.io/...
  traffic:
    - percent: 0
      revisionName: NAME-002
      tag: candidate
    - percent: 100
      revisionName: NAME-001
```

**Repository**

**Additional information**
