### ISSUE TITLE
Consider not requiring `image` and supporting build and deploy from source

### ISSUE THREAD

**Issue by steren** [google-github-actions/deploy-cloudrun#16]
I see that deploying to Cloud Run the action requires an `image` attribute. That makes sense if the user wants to use one step to build a container, and then another step deploy it.
```
steps:
- id: deploy
  uses: google-github-actions/deploy-cloudrun@main
  with:
    image: gcr.io/cloudrun/hello
    service: hello-cloud-run
    credentials: ${{ secrets.gcp_credentials }}
```

But we could imagine 
```
steps:
- id: deploy
  uses: google-github-actions/deploy-cloudrun@main
  with:
    service: hello-cloud-run
    credentials: ${{ secrets.gcp_credentials }}
```

Which would build and deploy the current repo.

Under the hood, `gcloud beta run deploy --source .` would be used.

**Comment by bharathkkb** [comment]
Thanks for the feedback @steren 
Is this exposed and built into the run API or does gcloud handle the orchestration of cloud build job in the background?

**Comment by averikitsch** [comment]
Currently under the hood, the action is using the Cloud Run API in order to remove the extra time of downloading and installing `gcloud`, which may make it harder to implement deploy from source. I should do some testing to see if there is really a difference because building off of gcloud would allow for quicker additions of new features. 

Just to note, I am looking to prioritize features such as revision tagging or setting revision suffix and deploying with no traffic to improve the CI/CD experience.

**Comment by steren** [comment]
This is something that gcloud orchestrates. The Cloud Run API is strictly focuses on container images.

But that doesn't mean this action has to take a dependency on gcloud. It could issue a regular docker build if no image is passed. Up to you if you want to keep it simple or have it handle more of the build.

To help the usability of this action, I suggest to better document in it's readme the typical other actions used to build images and pushing the to Artifact Registry.

**Comment by zrosenbauer** [comment]
Just looked at this, IMO as developer I'd rather build & push separate:

```yaml
  buildAndPush:
    steps:
      # ... removed intermediate
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/${{ secrets.GCP_OPS_PROJECT_ID }}/preview-${{ fromJSON(steps.parseConfig.outputs.contents).name }}:${{ github.sha }}
```

Full Example: https://github.com/bluenovaio/launchpad-example/blob/main/.github/workflows/launchpad-ci.yaml#L66

Are you planning on adding this in by default?
