### ISSUE TITLE
How do I get this action to send traffic to my new revision?

### ISSUE THREAD

**Issue by tubbo** [google-github-actions/deploy-cloudrun#168]
I have the following step in my workflow:

```yaml
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: cathode
          image: gcr.io/nsg-lobby/cathode:${{ steps.get_version.outputs.VERSION }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          region: us-east4
```

I see the revisions being deployed in Cloud Run, but they never get traffic assigned to them. I have to manually assign traffic in the UI in order for any of the revisions to be active at our URL. Is there any way I can make this action send all traffic to the new revision every time it's deployed? From the documentation that looked like it was the default behavior, but I don't see that in action on my Google Cloud account...
