### ISSUE TITLE
Permission 'run.services.get' denied on resource 'namespaces/***/services/***' (or resource may not exist).

### ISSUE THREAD

**Issue by igorkf** [google-github-actions/deploy-cloudrun#182]
### Question
I'm having this problem when setting a Github Actions:
```
ERROR: (gcloud.run.deploy) PERMISSION_DENIED: Permission 'run.services.get' denied on resource 'namespaces/***/services/***' (or resource may not exist).
```

My `.yml` is as follows:
```
name: Cloud Run Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
  
    name: Setup Cloud Run Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ secrets.GCP_APP_NAME }} \
            --region us-central1 \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }} \
            --platform managed
```

Am I doing something wrong?   
I created a service account with some roles, like:
- Cloud Run Admin
- Service Account User
- Storage Admin

I created some secrets as well, as the documentation states.    
Thank you.
