### ISSUE TITLE
Action fails to manage traffic

### ISSUE THREAD

**Issue by tubbo** [google-github-actions/deploy-cloudrun#202]
### TL;DR

When `deploy-cloudrun` executes, using default settings, it doesn't manage traffic and actually send requests to the new container.

**Expected behavior**

I expected `deploy-cloudrun` to work just like the manual Cloud Run interface: When a deploy happens, if I don't specify traffic settings, send 100% of traffic to the new container.

**Observed behavior**

It just deploys the container and walks away. You have to go into the admin and manually send traffic to the new container.

### Reproduction

**Action YAML**

```yaml
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: my-service
          image: gcr.io/my-project/my-service:${{ steps.get_version.outputs.VERSION }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          region: us-east4
```

**Additional information**

N/A
