### ISSUE TITLE
The wrong service account is being used

### ISSUE THREAD

**Issue by jmn** [google-github-actions/deploy-cloudrun#21]
### TL;DR
Somehow the wrong service account is being used, I have tried both using credentials file directly and using `setup-gcloud` export.

**Expected behavior**
The service account in my json secret should be used.

**Observed behavior**
Another service account was used (project default or other?). I was getting the message `ERROR: (gcloud.beta.run.deploy) PERMISSION_DENIED: Permission 'iam.serviceaccounts.actAs' denied on service account cloudrun-berglas-tide@b-myproject-net.iam.gserviceaccount.com (or it may not exist).`  I guess it was a permissions error where my Service Account was trying to `actAs` another service account. 

### Reproduction

**Action YAML**

```yaml
# .github/workflows/ci.yml

name: Earthly CI with Google Cloud Run deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v2
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Login to GAR
      uses: docker/login-action@v1
      with:
        registry: europe-north1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}
    - name: Download latest earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.4.4/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
    - name: Earthly version
      run: earthly --version
    - name: Run build
      run: earthly --push +docker-google
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - id: Deploy
      uses: google-github-actions/deploy-cloudrun@main
      with:
        image: europe-north1-docker.pkg.dev/b-jmnorlund-net/tide/jmnoz/tide-tera:latest
        service: tide
        region: europe-north1
        credentials: ${{ secrets.GCP_SA_KEY }}
```

**Repository**
https://github.com/jmn/tide-tera

**Additional information**
Using Earthly build tool
