### ISSUE TITLE
Unclear Error: Request has Errrors with google-github-actions/deploy-cloudrun@v0.2.0

### ISSUE THREAD

**Issue by aflmp** [google-github-actions/deploy-cloudrun#22]
### Question

I'm trying to deploy the below configuration using `google-github-actions/deploy-cloudrun@v0.2.0`
```
gcloud run deploy xyz-service \
  --image gcr.io/x/y:z \
  --region us-central1 \
  --platform managed \
  --max-instances 1 \
  --port 443 \
  --allow-unauthenticated 
```
with the following workflow and service.yaml. 

workflow.yaml
```yaml
- name: deploy to Cloud Run
  id: deploy
    uses: google-github-actions/deploy-cloudrun@v0.2.0
    with:
      service: xyz-service
      image: gcr.io/x/y:z
      region: us-central1
            

```

service.yaml
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: xyz-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1' 
    spec:
      containers:
      - image: gcr.io/x/y:z
      - env:
        - PORT: 443
```

I'm getting back
```
Error: Error: The request has errors
Error: The request has errors
```

Not sure if it's a limitation or am I doing something wrong?
