### ISSUE TITLE
The feature 'sandbox selector' is not supported in the declared launch 

### ISSUE THREAD

**Issue by rainy-me** [google-github-actions/deploy-cloudrun#26]
Hello, I've been using this action since last week and everything worked just fine. But since today some errors happen and fail to depoly the image.

**Expected behavior**

It depolys new cloud run images successfully.

**Observed behavior**

```
Run google-github-actions/deploy-cloudrun@v0.2.0
  with:
    service: ***
    image: asia.gcr.io/***/***:299faf0ea2878d743045b2ab96914290c774e633
    region: asia-northeast1
  env:
    PROJECT_ID: ***
    SERVICE: ***
    SA_KEY: ***
    REGION: asia-northeast1
    IMAGE: asia.gcr.io/***/***
    CLOUDSDK_METRICS_ENVIRONMENT: github-actions-setup-gcloud
    GCLOUD_PROJECT: ***
    GOOGLE_APPLICATION_CREDENTIALS: /home/runner/work/***/***/0dfa6524-a860-4607-bebf-c46a81b38eaa
Setting project Id from $GCLOUD_PROJECT
Creating a service revision...
Error: Error: The feature 'sandbox selector' is not supported in the declared launch stage on resource ***. The launch stage annotation should be specified at least as BETA. Please visit https://cloud.google.com/run/docs/troubleshooting#launch-stage-validation for in-depth troubleshooting documentation.
Error: The feature 'sandbox selector' is not supported in the declared launch stage on resource ***. The launch stage annotation should be specified at least as BETA. Please visit https://cloud.google.com/run/docs/troubleshooting#launch-stage-validation for in-depth troubleshooting documentation.
```

I visited the  https://cloud.google.com/run/docs/troubleshooting#launch-stage-validation page but found nothing I can do as a user of this action.

### Reproduction

**Action YAML**

https://github.com/rainy-me/tsukiyo/blob/master/.github/workflows/depoly-backend.yml

```yaml
name: Deploy Backend Cloud Run

on:
  push:
    branches:
      - master

# adapted form https://github.com/google-github-actions/deploy-cloudrun/blob/main/.github/workflows/example-workflow.yaml
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: ${{ secrets.GCP_SERVICE }}
  SA_KEY: ${{ secrets.GCP_SA_KEY }}
  REGION: asia-northeast1
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_SERVICE }}

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ env.SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |
          docker pull ${{ env.IMAGE }}-cache || true
          docker build . -t ${{ env.IMAGE }}:${{  github.sha }} -f Dockerfile.prod --cache-from=${{ env.IMAGE }}-cache
          docker push ${{ env.IMAGE }}:${{  github.sha }} || true
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE }}:${{ github.sha }}
          region: ${{ env.REGION }}

      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'deploy-backend',
              icon_emoji: ':actix:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `Deploy backend done in ${process.env.AS_TOOK} :actix:`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
```

**Repository**

https://github.com/rainy-me/tsukiyo

specifically the `depoly-backend` action

**Additional information**
