### ISSUE TITLE
Project ID ignored in 0.7.0

### ISSUE THREAD

**Issue by knowhoper** [google-github-actions/deploy-cloudrun#276]
### TL;DR

It appears that the project_id parameter is now ignored ie:

```
        - name: Deploy to Cloud Run
          uses: google-github-actions/deploy-cloudrun@v0.3.0
          with: 
              region: australia-southeast1
              project_id: xxx-development
              metadata: ./service-definition-updated.yaml
```

Works, the following does not

```
        - name: Deploy to Cloud Run
          uses: google-github-actions/deploy-cloudrun@v0.7.0
          with: 
              region: australia-southeast1
              project_id: xxx-development
              metadata: ./service-definition-updated.yaml
```

### Expected behavior

Deployment to succeed.  This is an issue when authenticating within one project to use a service account to deploy to another project.

### Observed behavior

Deployment fails. 

### Action YAML

```yaml
name: Staging - Publish to Cloud Run

on:
 push:
   tags:
     - 'staging*'
env:
  IMAGE_NAME: ${{ values.container }}
  IAM_ROLES: 'roles/run.invoker'
jobs:       
    build:
      name: Build and Push Container
      runs-on: ubuntu-latest
      permissions:
          id-token: write
          contents: write
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Authenticate to Google Cloud To Publish to Docker
          uses: google-github-actions/auth@v0.4.3
          with:
            workload_identity_provider: 'projects/xxx/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-provider'
            service_account: 'svc-docker-writer@acme-dev-tooling.iam.gserviceaccount.com'
          
        - name: Configure GCloud Auth provider with Docker
          run: |
                gcloud auth configure-docker australia-southeast1-docker.pkg.dev
        - name: Build Tag & Push Container
          run: | 
                  tagname=${{ github.ref_name }}
                  docker build -t ${{ env.IMAGE_NAME}} --target prod .
                  docker tag ${{ env.IMAGE_NAME}} australia-southeast1-docker.pkg.dev/acme-dev-tooling/acme-docker/${{ env.IMAGE_NAME}}:$tagname
                  docker push australia-southeast1-docker.pkg.dev/acme-dev-tooling/acme-docker/${{ env.IMAGE_NAME}}:$tagname           
    publish:
      needs: build
      runs-on: ubuntu-latest
      permissions:
          id-token: write
          contents: write
      steps: 
        - name: Checkout
          uses: actions/checkout@v2

        - name: Authenticate to Google Cloud To Read Secrets
          uses: google-github-actions/auth@v0.4.3
          with:
            workload_identity_provider: 'projects/xxx/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-provider'
            service_account: 'svc-secrets-reader@acme-dev-tooling.iam.gserviceaccount.com'

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.9.0'
        - name: Install Requirements & Create Service Definition
          run: |
              pip install -r requirements.txt 
              python createServiceDefinition.py
          env:        
            TAG: '${{ github.ref_name }}'
            ENVIRONMENT: dev

        - name: Authenticate to Google Cloud To Deploy To Cloud Run
          uses: google-github-actions/auth@v0.4.3
          with:
            credentials_json: '${{ secrets.GOOGLE_CLOUD_RUN_DEPLOYER_DEV_KEYFILE_JSON }}'

        # TODO: figure out why using WLIF seems to ignore the project_id here and fails - if you upgrade the version to 0.7.0

        - name: Deploy to Cloud Run
          uses: google-github-actions/deploy-cloudrun@v0.3.0
          with: 
              region: australia-southeast1
              project_id: acme-development
              metadata: ./service-definition-updated.yaml

        - name: Authenticate to Google Cloud To Create Service Account
          id: 'auth'
          uses: google-github-actions/auth@v0.4.3
          with:
            token_format: 'access_token'
            access_token_lifetime: '300s'
            workload_identity_provider: 'projects/xxx/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-provider'
            service_account: 'svc-iam-creator-dev@acme-dev-tooling.iam.gserviceaccount.com'

        - name: Create Service Account
          run: |
              python createServiceAccount.py
          env:        
            ENVIRONMENT: dev
            ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
        
        - name: Bind IAM roles # using environment variables setup in the last step.
          run: | 
                 gcloud run services add-iam-policy-binding ${{ env.SERVICE_NAME }} --project=acme-development --region=australia-southeast1 --member='serviceAccount:${{ env.SERVICE_EMAIL }}' --role='roles/run.invoker'
              # additional gcloud commands here do not bind. TODO: find workaround.
```

### Additional information

I use service accounts from a centralised project with specific permissions in other projects to deploy workloads to different environments. This is not possible using 0.7.0.

**Comment by sethvargo** [comment]
Can you please share your _complete_ action.yml file and any output. If the repo is public, can you please link to the failed run?

**Comment by knowhoper** [comment]
Done!

**Comment by justinkwanlee** [comment]
I am also experiencing this issue, tried with both 0.6.0 and 0.7.0.

Unlike the poster above, I couldn't downgrade to 0.3.0

```
name: Build, Publish and Deploy to Cloud Run

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master      

env:  
  GCP_CLOUD_RUN_SERVICE: <my-cloud-run-service-name>
  GCP_REGION: <my-region>
  GCP_ARTIFACT_REGISTRY_REPOSITORY: <my-registry-repo>
  GCP_ARTIFACT_REGISTRY_IMAGE: <my-registry-image>
  GCP_BUILD_TOOLS_PROJECT_ID: ${{ secrets.GCP_BUILD_TOOLS_PROJECT_ID }}
  GCP_CLOUD_RUN_PROJECT_ID: ${{ secrets.GCP_CLOUD_RUN_PROJECT_ID }}

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build-publish:
    name: Build & Publish
    runs-on: ubuntu-latest    
    steps:
      ....

  deploy:
    name: Deploy
    runs-on: ubuntu-latest    
    needs: build-publish
    steps:
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          token_format: "access_token"    
      # Deploy the Docker image to Cloud Run
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.4.0 # Issue with Project ID being ignored, so use older versionhttps://github.com/google-github-actions/deploy-cloudrun/issues/276
        with:
          service: ${{ env.GCP_CLOUD_RUN_SERVICE }}
          image: "${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_BUILD_TOOLS_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REGISTRY_REPOSITORY }}/${{ env.GCP_ARTIFACT_REGISTRY_IMAGE }}:${{ github.sha }}"
          region: ${{ env.GCP_REGION }}
          project_id: ${{ env.GCP_CLOUD_RUN_PROJECT_ID }}
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
````
