### ISSUE TITLE
Create property to manage cloud run attachments

### ISSUE THREAD

**Issue by steveoh** [google-github-actions/deploy-cloudrun#313]
### TL;DR

gcloud run deploy offers add remove set and clear-cloudsql-instances flags. It seems that this should be a first class property like secrets and env's for this action.

### Detailed design

This could be improved 

```yml
      - name: 🚀 Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: api
          image: gcr.io/...
          flags: |
            --set-cloudsql-instances=project:region:db
          env_vars: |
            A=B
          secrets: |
            /secrets/thing=thing:latest
```

to something like this

```yml
      - name: 🚀 Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: api
          image: gcr.io/...
          env_vars: |
            A=B
          secrets: |
            /secrets/thing=thing:latest
          cloudsql: |
            project:region:db
```

### Additional information

Then the correct flag could be generated based on the existing conventions for env_vars and secrets
