### ISSUE TITLE
Can't update existing function

### ISSUE THREAD

**Issue by selfagency** [google-github-actions/deploy-cloudrun#336]
### TL;DR

I'm trying to use this action to update an already existing function in Cloud Functions but it's telling me that I have to create a new function instead.

### Expected behavior

To update my existing function.

### Observed behavior

```
Failed to create function, function csp-reports already exists under Gen 2 environment.
Please delete conflicting function first or deploy the function with a different name.
```

### Action YAML

```yaml
name: Deploy CSP Reports cloud function
on:
  workflow_dispatch:
    inputs:
      environment:
        description: The environment to deploy to
        type: choice
        options:
          - staging
          - production
        default: staging
  push:
    branches:
      - main
    paths:
      - './cloud_functions/csp_reports/*'
concurrency:
  group: deploy-csp
  cancel-in-progress: true
jobs:
  deploy-csp-reports:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Authenticate to GCP Staging
        id: auth-staging
        uses: 'google-github-actions/auth@v0.7.0'
        if: ${{ github.event.inputs.environment == 'staging' }}
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER_STAGING }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_STAGING }}

      - name: Authenticate to GCP Production
        id: auth-production
        uses: 'google-github-actions/auth@v0.7.0'
        if: ${{ github.event.inputs.environment == 'production' }}
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER_PRODUCTION }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_PRODUCTION }}

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v0.9.0'
        with:
          name: 'csp-reports'
          runtime: 'nodejs16'
          source_dir: 'cloud_functions/csp_reports'
```

### Log output

```text
Extracted project ID 'unstoppable-domains-staging' from $GCLOUD_PROJECT
Created zip file from 'cloud_functions/csp_reports' at '/tmp/cfsrc-8d52d965f35eaeb0d8c14604.zip'
Creating new Cloud Function deployment
Error: google-github-actions/deploy-cloud-functions failed with: failed to POST https://cloudfunctions.googleapis.com/v1/projects/unstoppable-domains-staging/locations/us-central1/functions: unuccessful HTTP response: 400, body: {
  "error": {
    "code": 400,
    "message": "Failed to create function, function csp-reports already exists under Gen 2 environment. Please delete conflicting function first or deploy the function with a different name.",
    "status": "FAILED_PRECONDITION"
  }
}
```
