### ISSUE TITLE
Sandbox selector is not supported

### ISSUE THREAD

**Issue by gabac** [google-github-actions/deploy-cloudrun#36]
### TL;DR
The deploy action throws following error message
```Error: The feature 'sandbox selector' is not supported in the declared launch stage on resource cloud-run-demo. The launch stage annotation should be specified at least as BETA. Please visit https://cloud.google.com/run/docs/troubleshooting#launch-stage-validation for in-depth troubleshooting documentation.```

**Expected behavior**
Deployment to Google Cloud Run. It worked before

**Observed behavior**
Error as described on top

### Reproduction

**Action YAML**

```yaml
        - id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/cyril-test-project/cloud-run-demo
          service: cloud-run-demo```
```

**Repository**
not public

**Additional information**
No, I only did some manual deployment through the dashboard in the meantime like change the vCPUs
