### ISSUE TITLE
How to specify vpc-connector when deploying to cloud run.

### ISSUE THREAD

**Issue by mt185252** [google-github-actions/deploy-cloudrun#369]
### TL;DR

Hi There,
I was trying to deploy an image to GCP cloud run, using  this workflow.
My question is : 
How can I specify the vpc-connector to be used by my cloud run instance to connect to other services in a VPC shared with my project.

When I deploy using the GCP Console / UI, I specify it under connections tab.
Please refer to the attached screenshot below.
![image](https://user-images.githubusercontent.com/78864476/178451974-9f4f2312-7141-4cad-9065-ad4ba8496594.png)

**Comment by stefafafan** [comment]
[There isn't an input specific to VPC Connectors](https://github.com/google-github-actions/deploy-cloudrun#inputs) but, you can use the `flags` input to specify [options that can be used for gcloud run deploy](https://cloud.google.com/sdk/gcloud/reference/run/deploy#FLAGS).

[gcloud run deploy has an option for VPC Connectors](https://cloud.google.com/sdk/gcloud/reference/run/deploy#--vpc-connector) so you could probably do something like,

```yaml
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/cloudrun/hello'
        flags: --vpc-connector=YOUR_VPC_CONNECTOR
```
