### ISSUE TITLE
Adding extra env vars on new revisions not working

### ISSUE THREAD

**Issue by jackuoll** [google-github-actions/deploy-cloudrun#373]
### TL;DR

env_vars uses --update-env-vars, which doesn't work for new env vars

### Expected behavior

When changing

```
env_vars: DJANGO_SETTINGS_MODULE=${{ inputs.django_settings_module }}
```
to
```
env_vars: DJANGO_SETTINGS_MODULE=${{ inputs.django_settings_module }},GOOGLE_CLOUD_PROJECT=${{ inputs.gcp_project }}
```

I would expect the new revision has the new environment variable GOOGLE_CLOUD_PROJECT

### Observed behavior

DJANGO_SETTINGS_MODULE was still the only env var. 

I found the reason for this to be that the command generated by deploy-cloudrun is using `--update-env-vars` which means any new environment variables are not added. I needed to manually run the same command with --set-env-vars to get the new environment variable to appear in Cloud Run.

### Action YAML

```yaml
name: Deploy to GCP
description: Deploy

inputs:
  gcp_project:
    description: 'The GCP project to push to'
    required: true
  credentials:
    description: 'GCP Credentials'
    required: true
  github_actor:
    description: The github actor
    required: true
  github_token:
    description: The github token
    required: true
  commit_hash:
    description: 'Commit hash to push - must have been already built'
    required: true
  source_image:
    description: 'Name of image to pull from'
    required: true
  image_name:
    description: 'Name of image (ie: cinch-hr)'
    required: true
  django_settings_module:
    description: 'The django settings module full path'
    required: true
  from_registry:
    description: 'Where to get the image from'
    default: ghcr.io
    required: false
  to_registry:
    description: 'Where to push the image to'
    default: australia-southeast1-docker.pkg.dev
    required: false


runs:
  using: "composite"
  steps:
    - name: Login GCP
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ inputs.credentials }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        install_components: beta

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.from_registry }}
        username: ${{ inputs.github_actor }}
        password: ${{ inputs.github_token }}

    - name: 'Push Image'
      shell: bash
      run: |
        docker pull ${{ inputs.from_registry }}/${{ inputs.source_image }}:${{ inputs.commit_hash }}
        gcloud auth configure-docker ${{ inputs.to_registry }}
        docker tag ${{ inputs.from_registry }}/${{ inputs.source_image }}:${{ inputs.commit_hash }} ${{ inputs.to_registry }}/${{ inputs.gcp_project }}/${{ inputs.image_name }}/${{ inputs.image_name }}:${{ inputs.commit_hash }}
        docker push ${{ inputs.to_registry }}/${{ inputs.gcp_project }}/${{ inputs.image_name }}/${{ inputs.image_name }}:${{ inputs.commit_hash }}

    - name: 'Delete old migration job'
      shell: bash
      run: gcloud beta run jobs delete django-migrate --region=australia-southeast1 --quiet
      continue-on-error: true

    - name: 'Create and run migration job'
      shell: bash
      run: |
        gcloud beta run jobs create django-migrate --image ${{ inputs.to_registry }}/${{ inputs.gcp_project }}/${{ inputs.image_name }}/${{ inputs.image_name }}:${{ inputs.commit_hash }} \
          --set-secrets POSTGRES_PASSWORD=postgres-password:latest --args migrate --set-env-vars DJANGO_SETTINGS_MODULE="${{ inputs.django_settings_module }}" --set-cloudsql-instances=cloudrun-sql \
          --region=australia-southeast1 --quiet && \
        gcloud beta run jobs execute django-migrate --region=australia-southeast1 --wait

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: ${{ inputs.image_name }}
        image: ${{ inputs.to_registry }}/${{ inputs.gcp_project }}/${{ inputs.image_name }}/${{ inputs.image_name }}:${{ inputs.commit_hash }}
        flags: --args=prod --set-cloudsql-instances=cloudrun-sql --allow-unauthenticated
        env_vars: DJANGO_SETTINGS_MODULE=${{ inputs.django_settings_module }},GOOGLE_CLOUD_PROJECT=${{ inputs.gcp_project }}

        region: australia-southeast1
```
