### ISSUE TITLE
Custom revision name as action input

### ISSUE THREAD

**Issue by tobbbles** [google-github-actions/deploy-cloudrun#39]
### TL;DR
Hi! I want to give my revisisons a customised name from this action, whithout using a service.yaml metadata file.

### Design

**Action YAML**

The main use case here I see is including the commit hash from the Actions runner in the revision name, something like the following:

```yaml
    - name: deploy
      uses: google-github-actions/deploy-cloudrun@main
      with:
        region: ${{ env.REGION }}
        image: gcr.io/cloudrun/hello
        revision: hello-${{ github.sha }}
```

With the resulting revision being resembling `hello-18c8429f46c5f2717aece30ec83cf83d04943fda`

**Resources**
N/A

**Additional information**

There may be a limit on the revision name, and unfortuantely it's not trival to get a short commit hash directly from GitHub, so that could be a blocker here.
