### ISSUE TITLE
Incorrect IAM permissions in the starter workflow

### ISSUE THREAD

**Issue by ianyoung** [google-github-actions/deploy-cloudrun#423]
### TL;DR

Deployment fails when deploying to Cloud Run from source with using the default template.

### Expected behavior

Successful deploy

### Observed behavior

Failure to deploy with the following error message:

```
Error: google-github-actions/deploy-cloudrun failed with: failed to execute gcloud command `gcloud run deploy MY-SERVICE --quiet --platform managed --region europe-west6 --source ./src/ --project *** --format json`: This command is equivalent to running `gcloud builds submit --tag [IMAGE] ./src` and `gcloud run deploy MY-SERVICE --image [IMAGE]`
```
_The name of my service has been replaced with `MY-SERVICE`_

### Action YAML

```yaml
name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} # Google Cloud project id
  SERVICE: MY-SERVICE
  REGION: europe-west6

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If required, update to the appropriate source folder
          source: ./src/

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
```

### Additional information

Steps followed:

1. Go to GitHub Actions tab in my repo
2. Create new workflow
3. Select "configure" on "Build and deploy from source" ([screenshot](https://d.pr/i/iEZLR9))
4. Update env vars 

I'm looking to use my own Dockerfile in `./src/`. I've updated the `source` parameter accordingly: `source: ./src/`.
I've also tried removing the trailing slash. This results in the same error.

I've used a different service name to ensure it's unique and the error is the same.
