### ISSUE TITLE
Cannot deploy if an environment variable contains a comma

### ISSUE THREAD

**Issue by Kliton** [google-github-actions/deploy-cloudrun#425]
### TL;DR

Commas in environment variables brings to error: `google-github-actions/deploy-cloudrun failed with: failed to read file '.env': failed to parse KEY=VALUE pair "example": missing "="`

### Expected behavior

Escape commas

### Observed behavior

Cannot deploy

### Action YAML

```yaml
- name: Deploy to Cloud Run
        id: deploy_cloud_run
        uses: google-github-actions/deploy-cloudrun@v1.0.0
        with:
          service: ${{ env.SERVICE }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
          region: ${{ env.REGION }}
          port: ${{ env.APP_PORT }}
          env_vars_file: .env
```

### Log output

```text
`google-github-actions/deploy-cloudrun failed with: failed to read file '.env': failed to parse KEY=VALUE pair "example": missing "="`
```
