### ISSUE TITLE
When specifying metadata yaml, region is ignored

### ISSUE THREAD

**Issue by applovinjake** [google-github-actions/deploy-cloudrun#437]
### TL;DR

The docs claim "When using a custom metadata YAML file, all other inputs are ignored". This is not true of the `region` key, instead using the default `us-central1` region.

### Expected behavior

The `metadata.labels.cloud.googleapis.com/location` key is used for `region` when a metadata yaml file is specifed

### Action YAML

```yaml
- name: Deploy to Cloud Run
  id: deploy
  uses: google-github-actions/deploy-cloudrun@v1
  with:
    metadata: ./docker/images/ui-dash/service.yaml
```

```yaml
apiVersion: 'serving.knative.dev/v1'
kind: 'Service'
metadata:
  name: 'uidash'
  labels:
    cloud.googleapis.com/location: 'us-east1'
```

### Log output

```text
Error: google-github-actions/deploy-cloudrun failed with: failed to execute gcloud command `gcloud run services replace ./docker/images/ui-dash/service.yaml --platform managed --format json --region us-central1`: Applying new configuration to Cloud Run service [uidash] in project [prj-al-d-dash-1966] region [us-central1]
```
