### ISSUE TITLE
Attempting to deploy with deploy-cloudrun results in 'the request has errors'.

### ISSUE THREAD

**Issue by joshourisman** [google-github-actions/deploy-cloudrun#44]
### Question

Using the example workflow (included below), and changing only the necessary environment variables and secrets as described in the setup instructions, the Deploy to Cloud Run step fails with the unhelpful message `The request has errors`. The example workflow specifies deploy-cloudrun@0.2.0, but I've also tried with 0.3.0 and 0.4.0, with the same results.

```yaml
on:
  push:
    branches:
      - push-deploy

name: Build and Deploy a Container
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  SERVICE: my-test-service
  REGION: us-east4

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true # Set to true to authenticate the Cloud Run action

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} frontend/ -f frontend/Dockerfile
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.2.0
        with:
          service: ${{ env.SERVICE }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
          region: ${{ env.REGION }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
```
