### ISSUE TITLE
Cannot pass arguments beginning with a hyphen in --args

### ISSUE THREAD

**Issue by Pascal-Delange** [google-github-actions/deploy-cloudrun#444]
### TL;DR

I cannot pass arguments starting with a hyphen (say, -run_server) in the --args. Indeed, it translates it to the gcloud command `--args -run_server` which then complains about no value found in --args. The correct syntax here would be to translate it to `--args=run_server` which works.

### Expected behavior

`flags: --args=-server`  gets translated to the gcloud argument `--args -server`, which fails because of the hyphen

### Observed behavior

The "=" between --args and the actual args should remain there

### Action YAML

```yaml
- name: Deploy server
     uses: "google-github-actions/deploy-cloudrun@v1"
     with:
       service: service-name
       image: my-image
       region: my-region
       flags: --args="-server"
```

### Additional information

In the end I just fell back to standard gcloud commands, since I also need to deploy a Cloud Run job anyway.
