### ISSUE TITLE
env_vars_file deprecated?

### ISSUE THREAD

**Issue by cgeudens** [google-github-actions/deploy-cloudrun#459]
### TL;DR

The documentation says that `env_vars_file` is one of the optional parameters that can be added to a GitHub Actions workflow. However, deployments to Cloud Run fail when using this parameter.

### Observed behavior

I get the following warning: 
```
Warning: Unexpected input(s) 'env_vars_file', valid inputs are ['image', 'service', 'region', 'env_vars', 'secrets', 'labels', 'metadata', 'project_id', 'credentials', 'source', 'suffix', 'tag', 'timeout', 'no_traffic', 'revision_traffic', 'tag_traffic', 'flags', 'gcloud_version', 'gcloud_component']
```
Is the documentation no longer up to date? And what is the best practice in case you need to pass a large number of env vars to Cloud Run?

### Action YAML

```yaml
- name: Deploy to Cloud Run - Main
  if: github.ref == 'refs/heads/main'
  id: deploy-main
  uses: google-github-actions/deploy-cloudrun@v0
  with:
    env_vars_file: path/to/env/vars/file
    service: my_service
    region: ${{ env.REGION }}
    image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/my_service:${{ github.sha }}
    secrets: |
      MY_SECRET=MY_SECRET:latest
```
