### ISSUE TITLE
Error: failed to parse KEY=VALUE pair "test"": missing "="

### ISSUE THREAD

**Issue by spixy** [google-github-actions/deploy-cloudrun#462]
### TL;DR

```yml
uses: "google-github-actions/deploy-cloudrun@v1"
with:
  env_vars: |
    PARTNERS="TEST,test"
```
causes Github Actions to fail with
> Error: failed to parse KEY=VALUE pair "test"": missing "="

I also tried:
```yml
PARTNERS=TEST,test
"PARTNERS=TEST,test"
```

### Expected behavior

To successfully finish step.

### Action YAML

```yaml
on:
  workflow_call:
    inputs:
      PARTNERS :
        required: true
        type: string

jobs:
  deploy:
    permissions:
      ...
    runs-on: ubuntu-latest
    environment: ...
    steps:
      ...
      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ...
      - name: Deploy to Cloud Run
        id: deploy
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ...
          region: ...
          image: ...
          env_vars: |
            ...
            PARTNERS="${{ inputs.PARTNERS }}"
            ...
          flags: |
            ...
```

### Log output

```text
Run google-github-actions/deploy-cloudrun@v1
  with:
    service: ...
    region: ...
    image: ...
    env_vars: ...
  ...
  PARTNERS="TEST,test"
  ...  
    flags: ...
    skip_default_labels: false
    no_traffic: false
  env:
    CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE: /abc.json
    GOOGLE_APPLICATION_CREDENTIALS: def.json
    GOOGLE_GHA_CREDS_PATH: ghi.json
    CLOUDSDK_CORE_PROJECT: ...
    CLOUDSDK_PROJECT: ...
    GCLOUD_PROJECT: ...
    GCP_PROJECT: ...
    GOOGLE_CLOUD_PROJECT: ...
Error: google-github-actions/deploy-cloudrun failed with: failed to parse KEY=VALUE pair "test"": missing "="
```
