### ISSUE TITLE
No effect of --allow-unauthenticated flag

### ISSUE THREAD

**Issue by yzakharyk** [google-github-actions/deploy-cloudrun#473]
### TL;DR

Even after setting `--allow-unauthenticated` flag my newly created service still requires authentication

### Expected behavior

Service is publicly accessible to anyone on the internet with no authentication required.

### Observed behavior

Authentication of service is required and it's not publicly accessible to anyone on the internet.

### Action YAML

```yaml
- name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}
          flags: '--allow-unauthenticated --min-instances=1 --max-instances=1'
```
