### ISSUE TITLE
Cannot use env with no value

### ISSUE THREAD

**Issue by spixy** [google-github-actions/deploy-cloudrun#488]
### TL;DR

Empty env makes action to crash.

### Expected behavior

Set env to empty value. (like `export TEST_ENV=`)

### Observed behavior

Error

### Action YAML

```yaml
on:
 workflow_call:
  inputs:
    ENV_DEBUG_OVERWRITE:
      required: false
      type: string


jobs:
 deploy:
  runs-on: ubuntu-latest
  environment: ${{ inputs.ENVIRONMENT }}
  steps:
  - name: Deploy
     uses: "google-github-actions/deploy-cloudrun@v1"
     with:
       env_vars: |
         ENV_DEBUG_OVERWRITE=${{ inputs.ENV_DEBUG_OVERWRITE}}
```

### Log output

```text
Run google-github-actions/deploy-cloudrun@v1
  with:
    service: ...
    region: ...
    image: ...
    env_vars:
  ENV_DEBUG_OVERWRITE=
  
    secrets: ...
  
    skip_default_labels: false
    no_traffic: false
  env:
    ...
Error: google-github-actions/deploy-cloudrun failed with: failed to parse KEY=VALUE pair "ENV_DEBUG_OVERWRITE=": no value
```
