### ISSUE TITLE
metadata don't works when input job yaml

### ISSUE THREAD

**Issue by templarfelix** [google-github-actions/deploy-cloudrun#508]
### TL;DR

I have metadata for job, but the actions only allow knative yaml.

```
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: job
  labels:
    run.googleapis.com/satisfiesPzs: 'true'
    cloud.googleapis.com/location: southamerica-east1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      parallelism: 1
      taskCount: 1
      template:
        spec:
          containers:
            - image: us-docker.pkg.dev/xxx/docker/job:latest
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 1000m
                  memory: 512Mi
          maxRetries: 0
          timeoutSeconds: '3600'
```

### Expected behavior

Accept yaml of job and knative.

### Observed behavior

google-github-actions/deploy-cloudrun failed with: failed to execute gcloud command `gcloud run services replace ./scripts/job/Service.dev.yaml --format json --region southamerica-east1`: ERROR: (gcloud.run.services.replace) Failed to parse value(s) in protobuf [Service]: Service.spec.template.spec.***parallelism,taskCount,template***

### Action YAML

```yaml
- 
        name: Deploy Cloud Run Application with Metadata
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          region: '${{ inputs.app_region }}'
          metadata: '${{ inputs.cloud_run_metadata }}'
```
