### ISSUE TITLE
Cloud run job issue with parsing flags

### ISSUE THREAD

**Issue by AdeelK93** [google-github-actions/deploy-cloudrun#514]
### TL;DR

This GHA replaces `=` separated flags with space separate flags, which can cause parsing issues. 

### Expected behavior

If I add in the flags `--command=python --args='-m,job.main'`, the output gcloud command should also be `=` separated, which would result in a successful deploy.

### Observed behavior

The `=` gets replaced by a space by GHA, and the resultant flag sent to gcloud looks like `--command python --args -m,job.main`. That leading dash for `-m` causes a shell parsing error, which looks like:
> ERROR: (gcloud.run.jobs.deploy) argument --args: expected one argument

### Action YAML

```yaml
- name: Deploy to Cloud Run
  uses: google-github-actions/deploy-cloudrun@v2
  with:
    job: test
    region: us-east1
    flags: --command=python --args=-m,job.main
```

### Log output

```text
Error: google-github-actions/deploy-cloudrun failed with: failed to execute gcloud command `gcloud run jobs deploy test ... --command python --args -m,job.main`: ERROR: (gcloud.run.jobs.deploy) argument --args: expected one argument
```

### Additional information

This is only an issue if the first arg starts with a dash

**Comment by sethvargo** [comment]
I believe you need to quote your command, same as in your shell:

```yaml
- name: Deploy to Cloud Run
  uses: google-github-actions/deploy-cloudrun@v2
  with:
    job: test
    region: us-east1
    flags: --command="python --args=-m,job.main"
```
