### ISSUE TITLE
`regions` property as CSV is broken

### ISSUE THREAD

**Issue by zekronium** [google-github-actions/deploy-cloudrun#530]
### TL;DR

The ability to provide a list of comma separated `region` does not seem to work

### Expected behavior

To deploy to multiple cloud run regions supplied by the `region` property

### Action YAML

```yaml
- id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/cloudrun/hello'
        region: us-east4,us-central1,asia-northeast1
```

### Log output

```text
##[error]google-github-actions/deploy-cloudrun failed with: failed to execute gcloud command `gcloud run deploy app --image us-east4-docker.pkg.dev/project/docker-images/busybox:latest --update-env-vars ^,^LOG_LEVEL=Error --update-labels ^,^managed-by=github-actions,commit-sha=REDACTED --format json --region us-east4,us-central1,asia-northeast1 --async`: ERROR: (gcloud.run.deploy) Invalid value for property [api_endpoint_overrides/run]: The endpoint_overrides property must be an absolute URI beginning with http:// or https:// and ending with a trailing '/'. [https://us-east4,us-central1,asia-northeast1-run.googleapis.com/] is not a valid endpoint override.
```
