### ISSUE TITLE
Commas in env_vars values split the variable 

### ISSUE THREAD

**Issue by kosta** [google-github-actions/deploy-cloudrun#541]
### TL;DR

```yaml
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/cloudrun/hello'
        env_vars: |
          MY_JSON={"a": 1, "b": 2}
```

leads to the cloud service yaml being:

```yaml
        - name: MY_JSON
          value: '{"a": 1'
        - name: '"b": 2}'
```

### Expected behavior

The variable is not split

```yaml
        - name: MY_JSON
          value: '{"a": 1, "b": 2}'
```

### Observed behavior

The variable is split, see TL;DR:

```yaml
        - name: MY_JSON
          value: '{"a": 1'
        - name: '"b": 2}'
```

### Action YAML

```yaml
See TL;DR:


    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/cloudrun/hello'
        env_vars: |
          MY_JSON={"a": 1, "b": 2}
```

### Log output

Log output shows "the problem right here":

```text
Successfully authenticated
Running: gcloud run deploy hello-cloud-run --image gcr.io/cloudrun/hello --set-env-vars ^,^MY_JSON={"a": 1, "b": 2}= --update-labels ^,^managed-by=github-actions,commit-sha=... --format json
```

### Additional information

I think it's funny

**Comment by sethvargo** [comment]
Correct, you need to escape the comma: https://github.com/google-github-actions/deploy-cloudrun?tab=readme-ov-file#user-content-env_vars

```yaml
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/cloudrun/hello'
        env_vars: |
          MY_JSON={"a": 1\, "b": 2}
```

**Comment by kosta** [comment]
Thank you for your quick reply and pointing me to the docs (where I hadnt spot the relevant info). I was able to fix my issue using this snippet:

```yaml
      - name: Replace commas in MY_JSON
        id: ecaped_my_json
        uses: actions/github-script@v7
        env:
          INPUT: ${{vars.MY_JSON}}
        with:
          result-encoding: string
          script: |
            return process.env.INPUT.replace(",", "\\,").replaceAll("\n","\\\n")
```

and then using `steps.ecaped_my_json.outputs.result`.

However, I would kindly ask you to reconsider the approach here. I think the user having to escape commas is not reasonable. Even more so in the light of [github actions _not_ having a replace function](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#functions).

I see how with the stringly format, line breaks break the input. So _ideally_, I would propose for `env_vars` to be a dict<string, string> instead of a string:

```yaml
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'hello-cloud-run'
        image: 'gcr.io/cloudrun/hello'
        env_vars: # <- Note: No pipe |, just an yaml object
          MY_JSON: '{"a": 1, "b": 2}'
          SOME_VAR_FROM_GITHUB_THAT_HAS_LINE_BREAKS_AND_COMMAS: ${{vars.my_var}}
```

The variable escaping would then be done by this `deploy-cloudrun` github action.

But I can see how that would be a breaking change. Still, I think this would be the correct way to approach this.

Alternatively, please reconsider at least escaping the commas. Otherwise it's very cumbersome to use this if you're maybe writing a reusable workflow or action and need to jump through hoops to escape the values you're passing to this `deploy-cloudrun` action.
