### ISSUE TITLE
[flags] - `--args` with equal seems to not be supported properly

### ISSUE THREAD

**Issue by AdrienFromToulouse** [google-github-actions/deploy-cloudrun#58]
### TL;DR
`--args` flags for args requiring equals **seems** to not be properly supported leading to the addition of extra single quotes.

**Expected behavior**
Should end-up generating a YAML file like:

```
args:
        - "--database-host=xxx.xxx.xxx.xx"
        - "--database-name=bar"
        - baz
```
**Observed behavior**

For instance:

```yaml
flags: '--args "--database-host=xxx.xxx.xxx.xx" --args "--database-name=bar" --args baz
```

Will end-up generating a YAML file like:

```
args:
        - '"--database-host=xxx.xxx.xxx.xx"'
        - '"--database-name=bar"'
        - baz
```

### Reproduction

**Action YAML**

```yaml
name: Deployment

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: europe-west4
  IMAGE_NAME: backend
  VERSION: staging
  BUILD_CACHE: /tmp/.buildx-cache

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_CACHE }}
          key: ${{ runner.os }}-buildx-${{ hashFiles('./build/Dockerfile') }}
          restore-keys: ${{ runner.os }}-buildx-

      - uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.16.2"
      - run: make test
      - run: make vet

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CLOUD_RUN_SA_KEY }}
          export_default_credentials: true

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CLOUD_RUN_SA_KEY }}

      - name: Build and Push Docker image | build-image
        uses: docker/build-push-action@v2
        with:
          file: ./build/Dockerfile
          context: .
          target: build-image
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          cache-from: type=local,src=${{ env.BUILD_CACHE }}
          cache-to: type=local,dest=${{ env.BUILD_CACHE }}-new

      - name: Build and Push Docker image | deploy-image
        uses: docker/build-push-action@v2
        with:
          file: ./build/Dockerfile
          context: .
          target: deploy-image
          push: true
          tags: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          cache-from: type=local,src=${{ env.BUILD_CACHE }}
          cache-to: type=local,dest=${{ env.BUILD_CACHE }}-new

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf ${{ env.BUILD_CACHE }}
          mv ${{ env.BUILD_CACHE }}-new ${{ env.BUILD_CACHE }}

      - name: Deploy private API to Cloud Run
        id: deploy-private
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: ${{ env.VERSION }}-private-api
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          region: ${{ env.REGION }}
          flags: '--service-account=foo --args "--database-host=xxx.xxx.xxx.xx" --args "--database-name=bar" --args "--database-password=secret" --args "--database-user=me" --args private'

      - name: Output private API url
        run: curl "${{ steps.deploy-private.outputs.url }}"
```

**Additional information**
No
