### ISSUE TITLE
Ingress and Authentication Triggers

### ISSUE THREAD

**Issue by eb-trigo** [google-github-actions/deploy-cloudrun#69]
Hey,

I would like to know how can I set the **_Ingress_** to "Allow internal traffic only" (`--ingress internal`) and also the **_Authentication_** to "Allow unauthenticated invocations" (`--allow-unauthenticated`).
Without both settings, my pipeline would not work?

Thanks!

**Comment by vonNiklasson** [comment]
I believe you should be able to use the `flags` input to set additional parameters:

```yaml
- uses: google-github-actions/deploy-cloudrun@main
  with:
    flags: --ingress=internal --allow-unauthenticated
```
